/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_guangyang_testjni1_TestJNI */

#ifndef _Included_com_example_guangyang_testjni1_TestJNI
#define _Included_com_example_guangyang_testjni1_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_guangyang_testjni1_TestJNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_guangyang_testjni1_TestJNI_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
